"""mission_tables

Revision ID: 6f2b2fd5c9fe
Revises: c7db929421f6
Create Date: 2026-07-31 11:39:33.810085
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6f2b2fd5c9fe'
down_revision: Union[str, None] = 'c7db929421f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'IDLE'"), nullable=False),
    sa.Column('radius_meters', sa.Integer(), server_default=sa.text('20'), nullable=True),
    sa.Column('tty_port', sa.String(length=50), nullable=True),
    sa.Column('start_location_id', sa.Integer(), nullable=True),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('total_locations', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('visited_locations', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('IDLE','PLANNING','READY','STARTING','RUNNING','PAUSED','COMPLETED','STOPPED','FAILED')", name=op.f('ck_missions_status')),
    sa.CheckConstraint('radius_meters > 0', name=op.f('ck_missions_radius_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions')),
    schema='app'
    )
    op.create_index('idx_missions_current_loc', 'missions', ['current_location_id'], unique=False, schema='app')
    op.create_index('idx_missions_start_loc', 'missions', ['start_location_id'], unique=False, schema='app')
    op.create_index('idx_missions_status', 'missions', ['status'], unique=False, schema='app')
    op.create_table('mission_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('cellular_tower_id', sa.String(length=100), nullable=False),
    sa.Column('cellular_tower_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('upload_batch_id', sa.String(length=36), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('distance_from_previous_meters', sa.Float(), nullable=True),
    sa.Column('bearing_from_previous_degrees', sa.Float(), nullable=True),
    sa.Column('estimated_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_visit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_session_id', sa.Integer(), nullable=True),
    sa.Column('visited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','IN_PROGRESS','VISITED','SKIPPED')", name=op.f('ck_mission_locations_status')),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_mission_locations_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_mission_locations_longitude_range')),
    sa.ForeignKeyConstraint(['mission_id'], ['app.missions.id'], name=op.f('fk_mission_locations_mission_id_missions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_session_id'], ['app.scan_sessions.id'], name=op.f('fk_mission_locations_scan_session_id_scan_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_locations')),
    sa.UniqueConstraint('mission_id', 'cellular_tower_id', name='uq_mission_location_tower'),
    sa.UniqueConstraint('scan_session_id', name=op.f('uq_mission_locations_scan_session_id')),
    schema='app'
    )
    op.create_index('idx_mission_locations_batch', 'mission_locations', ['upload_batch_id'], unique=False, schema='app')
    op.create_index('idx_mission_locations_mission', 'mission_locations', ['mission_id'], unique=False, schema='app')
    op.create_index('idx_mission_locations_scan_session', 'mission_locations', ['scan_session_id'], unique=False, schema='app')
    op.create_index('idx_mission_locations_sequence', 'mission_locations', ['mission_id', 'sequence_order'], unique=False, schema='app')
    op.create_index('idx_mission_locations_status', 'mission_locations', ['status'], unique=False, schema='app')
    op.create_foreign_key(
        'fk_missions_start_location', 'missions', 'mission_locations',
        ['start_location_id'], ['id'], source_schema='app', referent_schema='app', ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_missions_current_location', 'missions', 'mission_locations',
        ['current_location_id'], ['id'], source_schema='app', referent_schema='app', ondelete='SET NULL',
    )
    conn = op.get_bind()
    result = conn.execute(
        sa.text("SELECT 1 FROM information_schema.columns "
                "WHERE table_schema='app' AND table_name='scan_sessions' "
                "AND column_name='mission_location_id'")
    )
    if result.scalar() is None:
        op.add_column('scan_sessions', sa.Column('mission_location_id', sa.Integer(), nullable=True), schema='app')
        op.create_index('ix_scan_sessions_mission_location_id', 'scan_sessions', ['mission_location_id'], unique=False, schema='app')
        op.create_foreign_key(
            op.f('fk_scan_sessions_mission_location_id_mission_locations'), 'scan_sessions', 'mission_locations',
            ['mission_location_id'], ['id'], source_schema='app', referent_schema='app', ondelete='SET NULL',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_scan_sessions_mission_location_id_mission_locations'), 'scan_sessions', schema='app', type_='foreignkey')
    op.drop_index('ix_scan_sessions_mission_location_id', table_name='scan_sessions', schema='app')
    op.drop_column('scan_sessions', 'mission_location_id', schema='app')
    op.drop_constraint('fk_missions_current_location', 'missions', schema='app', type_='foreignkey')
    op.drop_constraint('fk_missions_start_location', 'missions', schema='app', type_='foreignkey')
    op.drop_index('idx_mission_locations_status', table_name='mission_locations', schema='app')
    op.drop_index('idx_mission_locations_sequence', table_name='mission_locations', schema='app')
    op.drop_index('idx_mission_locations_scan_session', table_name='mission_locations', schema='app')
    op.drop_index('idx_mission_locations_mission', table_name='mission_locations', schema='app')
    op.drop_index('idx_mission_locations_batch', table_name='mission_locations', schema='app')
    op.drop_table('mission_locations', schema='app')
    op.drop_index('idx_missions_status', table_name='missions', schema='app')
    op.drop_index('idx_missions_start_loc', table_name='missions', schema='app')
    op.drop_index('idx_missions_current_loc', table_name='missions', schema='app')
    op.drop_table('missions', schema='app')
    # ### end Alembic commands ###
