"""initial tables

Revision ID: c7db929421f6
Revises: 
Create Date: 2026-07-27 15:08:49.137291
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c7db929421f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tty_port', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_sessions')),
    schema='app'
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings')),
    schema='app'
    )
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(length=100), nullable=True),
    sa.Column('mcc', sa.String(length=10), nullable=True),
    sa.Column('mnc', sa.String(length=10), nullable=True),
    sa.Column('rat', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['app.scan_sessions.id'], name=op.f('fk_scan_results_session_id_scan_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_results')),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_results', schema='app')
    op.drop_table('settings', schema='app')
    op.drop_table('scan_sessions', schema='app')
    # ### end Alembic commands ###
